### ISSUE TITLE
Cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' 

### ISSUE THREAD

**Issue by yoland68** [yoland68/comfy-cli#76]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yoland/opt/anaconda3/envs/comfyenv/lib/python3.11/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/Users/yoland/opt/anaconda3/envs/comfyenv/lib/python3.11/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/Users/yoland/opt/anaconda3/envs/comfyenv/lib/python3.11/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "/Users/yoland/opt/anaconda3/envs/comfyenv/lib/python3.11/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/Users/yoland/opt/anaconda3/envs/comfyenv/lib/python3.11/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
  File "charset_normalizer/md.py", line 5, in <module>
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (/Users/yoland/opt/anaconda3/envs/comfyenv/lib/python3.11/site-packages/charset_normalizer/constant.py)

**Comment by yoland68** [comment]
The solution is to upgrade the charset-normalizer to be >=3.0.0

**Comment by yoland68** [comment]
https://github.com/yoland68/comfy-cli/commit/a373fc75fdaf8989ca231e4afb0e8fe668cb9fc8
